#!/bin/sh -x
# $Id: mk,v 1.2 2013-03-26 17:59:00-07 - - $
PATH=$PATH:/afs/cats.ucsc.edu/courses/cmps012b-wm/bin
partnercheck 2>&1 | tee partnercheck.log
checksource README *.java Makefile 2>&1 | tee checksource.log
gmake 2>&1 | tee gmake.log
./hello 2>&1 | tee hello.log
